name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore BlazorTodo/BlazorTodo.csproj
    - name: Build
      run: dotnet build BlazorTodo/BlazorTodo.csproj --no-restore
    - name: Publish
      run: dotnet publish BlazorTodo/BlazorTodo.csproj -c Release -o release --nologo
    - name: Fix path and fix github pages shenanigans
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorWasmTodo\/" \/>/g' release/wwwroot/index.html && touch release/wwwroot/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: release/wwwroot
